import React, { createContext, useState, useContext, ReactNode } from 'react';

const translations = {
  en: {
    headerTitle: "NAIIP",
    settingsAriaLabel: "Settings",
    languageAriaLabel: "Language",
    // Dashboard
    dashboardTitle: "National AI Technology Development Project",
    dashboardSubtitle: "Select a service to get started.",
    asrTitle: "ASR System",
    asrDescription: "Transcribe Burmese speech to text.",
    translateTitle: "Machine Translation",
    translateDescription: "Translate between Burmese and English.",
    ttsTitle: "Text-to-Speech (TTS)",
    ttsDescription: "Convert Burmese text into natural-sounding speech.",
    ocrTitle: "Myanmar OCR",
    ocrDescription: "Extract text from Burmese images.",
    spellcheckTitle: "Myanmar Spellchecking System",
    spellcheckDescription: "Correct basic spelling mistakes in text.",
    agentTitle: "AI Agent Bot",
    agentDescription: "Access a suite of specialized AI assistants.",
    // Back Button Aria
    backToDashboard: "Back to Dashboard",
    backToAgent: "Back to Agent Dashboard",
    backToTTS: "Back to TTS Models",
    back: "Back",
    // ASR Page
    asrPageTitle: "Myanmar ASR System",
    asrPageSubtitle: "Automatic speech to text transcription system",
    asrLoading: "Processing...",
    asrPleaseWait: "Please wait",
    asrErrorOccurred: "Error Occurred",
    asrDropzonePrompt: "Drag & drop your file here",
    asrOr: "or",
    asrBrowse: "Browse for a file",
    asrStopRecording: "Stop recording",
    asrStartRecording: "Start recording",
    asrResultHeader: "Transcription Result",
    asrSpellCheck: "Myanmar Spellchecking System",
    asrCopyToClipboard: "Copy to Clipboard",
    asrPlaceholder: "Your transcribed text will appear here...",
    asrAudioError: "Your browser does not support the audio element.",
    asrFooter: "© 2025 Created by NAIIP. All rights reserved.",
    asrMicError: "Microphone access was denied. Please allow microphone access in your browser settings.",
    asrFileError: "Please drop an audio file.",
    // Machine Translate Page
    mtPageTitle: "Machine Translation",
    mtPageSubtitle: "Translate text from one language to another",
    mtLangMy: "Myanmar (မြန်မာ)",
    mtLangEn: "English",
    mtPlaceholderMy: "Enter text here (in Burmese)...",
    mtPlaceholderEn: "Enter text here (in English)...",
    mtResultPlaceholder: "Result will appear here...",
    mtTranslateButton: "Translate",
    mtSwap: "Swap languages",
    mtCopy: "Copy translated text",
    mtCopyError: "Could not copy text to clipboard.",
    mtFooter: "© 2025 Created by NAIIP. All rights reserved.",
    mtExampleText: "Example Texts",
    // Spellcheck Page (Gemini)
    spellcheckPageTitle: "Spell & Grammar Checker",
    spellcheckPageSubtitle: "Check for spelling mistakes with Gemini AI",
    spellcheckInputLabel: "Enter Text",
    spellcheckPlaceholder: "Enter text here...",
    spellcheckCheckButton: "Check Text",
    spellcheckResultHeader: "Text to Correct",
    spellcheckCopy: "Copy Corrected Text",
    spellcheckLoading: "Checking with Gemini AI...",
    spellcheckFooter: "© 2025 Created by NAIIP. All rights reserved.",
    spellcheckExampleText: "Example Texts",
    // TTS Dashboard
    ttsDashboardTitle: "Text-to-Speech (TTS)",
    ttsDashboardSubtitle: "Select a voice model to generate speech.",
    ttsCardModel1: "Model 1 (Parchoke Sayadaw)",
    ttsCardModel2: "Model 2 (Sitagu Sayadaw)",
    ttsCardModel3: "Model 3 (General Model)",
    // TTS Models (General)
    ttsModelTitlePrefix: "TTS:",
    ttsModel1Name: "Model 1 (Parchoke Sayadaw)",
    ttsModel2Name: "Model 2 (Sitagu Sayadaw)",
    ttsModel3Name: "Model 3 (General Model)",
    ttsInputLabel: "Enter Text",
    ttsPlaceholder: "Enter Burmese text here...",
    ttsRemoveSilence: "Remove Silence",
    ttsSpeed: "Speed:",
    ttsPhraseLimit: "Phrase Limit",
    ttsGenerateButton: "Generate Speech",
    ttsResultHeader: "Generated Audio",
    ttsLoadingPlaceholder: "Please wait....",
    ttsExampleText: "Example Text",
    ttsGender: "Gender",
    ttsMale: "Male",
    ttsFemale: "Female",
    // OCR Page
    ocrPageTitle: "Myanmar OCR",
    ocrPageSubtitle: "Extract Burmese text from images",
    ocrDropzone: "Select an image or drag it here",
    ocrOriginalHeader: "Original Image",
    ocrResultHeader: "Result Image",
    ocrOriginalPlaceholder: "Waiting for image selection",
    ocrResultPlaceholder: "OCR result will appear here",
    ocrExtractButton: "Extract Text",
    ocrProcessingButton: "Processing...",
    ocrClearButton: "Clear",
    ocrSuccessMessage: "Successfully extracted text from the image.",
    ocrClearedMessage: "All fields cleared.",
    ocrFileError: "Please select an image file.",
    ocrFooter: "© 2025 Created by NAIIP. All rights reserved.",
    // AI Agent Dashboard
    agentPageTitle: "AI Agent Bot",
    agentPageSubtitle: "Your suite of specialized AI assistants.",
    agentSummarizeTitle: "Myanmar Summarization",
    agentSummarizeDesc: "Condense long Burmese text into a short summary.",
    agentOcrTitle: "Myanmar OCR (Gemini)",
    agentOcrDesc: "Extract Burmese text from images using AI.",
    agentTranslateTitle: "Machine Translation",
    agentTranslateDesc: "Translate text between languages with Gemini.",
    agentSpeechTranslateTitle: "Speech to Translate",
    agentSpeechTranslateDesc: "Transcribe and translate speech in one step.",
    agentSpellcheckTitle: "Spell & Grammar Checker",
    agentSpellcheckDesc: "Correct mistakes in Burmese text using AI.",
    agentSttTitle: "Speech To Text",
    agentSttDesc: "Transcribe Burmese speech using Gemini.",
    agentTtsTitle: "Text To Speech",
    agentTtsDesc: "Generate natural-sounding Burmese speech.",
    agentNamingTitle: "Naming",
    agentNamingDesc: "Generate Burmese names based on traditions.",
    agentPdfTitle: "PDF Extractor",
    agentPdfDesc: "Extract text and insights from PDF documents.",
    agentLawAITitle: "Myanmar Law AI Chatbot",
    agentLawAIDesc: "Ask legal questions about Myanmar law.",
    agentS2sTitle: "Speech to Speech",
    agentS2sDesc: "Translate spoken language into another.",
    // Old Spellcheck Page
    oldSpellcheckTitle: "Myanmar Spellchecking System",
    oldSpellcheckSubtitle: "Checks for spelling mistakes.",
    oldSpellcheckResultHeader: "Corrected Text",
    oldSpellcheckLoading: "Checking for corrections...",
    oldSpellcheckFooter: "© 2025 Created by NAIIP. All rights reserved.",
    // Summarize Page
    summarizeTitle: "Myanmar Summarization",
    summarizeSubtitle: "Summarize long texts with Gemini AI",
    summarizeInputLabel: "Enter long text",
    summarizePlaceholder: "Paste the long text here...",
    summarizeButton: "Summarize Text",
    summarizeResultHeader: "Summary",
    summarizeLoading: "Summarizing with Gemini AI...",
    summarizeFooter: "© 2025 Created by NAIIP. All rights reserved.",
    // Agent OCR
    agentOcrPageTitle: "Myanmar OCR (Gemini)",
    agentOcrSubtitle: "Extract Burmese text from images using AI.",
    agentOcrUploadImageLabel: "1. Upload an Image",
    agentOcrDropzonePrompt: "Drag & drop an image here, or click to browse",
    agentOcrSelectedFile: "Selected file:",
    agentOcrOriginalImageLabel: "Original Image",
    agentOcrExtractedTextLabel: "Extracted Text",
    agentOcrPlaceholder: "Text will appear here after extraction...",
    agentOcrExtractButton: "Extract Text",
    agentOcrExtractingButton: "Extracting...",
    agentOcrCopyButtonTitle: "Copy Text",
    agentOcrErrorNotImage: "Please select a valid image file.",
    agentOcrErrorNoFile: "Please select an image file first to extract text.",
    agentOcrErrorUnknown: "An unknown error occurred during extraction.",
    // Agent Machine Translation
    agentMtTitle: "Machine Translation (Gemini)",
    agentMtSubtitle: "Translate between languages with Gemini AI",
    agentMtLangBurmese: "Burmese",
    agentMtLangEnglish: "English",
    agentMtPlaceholderBurmese: "Enter text here (in Burmese)...",
    agentMtPlaceholderEnglish: "Enter text here (in English)...",
    agentMtResultPlaceholder: "Translation will appear here...",
    // Speech to Translate Page
    sttPageTitle: "Speech to Translate (Gemini)",
    sttPageSubtitle: "Transcribe speech to text and translate",
    sttDropzonePrompt: "Drag & Drop Audio File",
    sttUpload: "or Click to Upload",
    sttRecord: "or Record",
    sttResultTranscription: "Transcription (Original)",
    sttResultTranslation: "Translation (English)",
    sttLoading: "Processing with Gemini AI...",
    sttMicError: "Microphone access was denied.",
    sttFileError: "Please drop an audio file.",
    // Agent Speech to Text
    agentSttPageTitle: "Speech to Text (Gemini)",
    agentSttPageSubtitle: "Transcribe Burmese audio with AI.",
    agentSttDropzonePrompt: "Drag & Drop Audio",
    agentSttChooseFile: "Choose a File",
    agentSttResultHeader: "Transcription Result",
    agentSttPlaceholder: "Your transcribed text will appear here...",
    agentSttLoading: "Transcribing with Gemini...",
    agentSttLoadingWait: "Please wait a moment.",
    // Agent Text to Speech
    agentTtsPageTitle: "Text-to-Speech",
    agentTtsPageSubtitle: "Generate natural-sounding speech from text.",
    agentTtsInputLabel: "Enter Text",
    agentTtsPlaceholder: "Enter text here...",
    agentTtsSettingsHeader: "Settings",
    agentTtsVoiceLabel: "Select Voice",
    agentTtsVoiceMale: "Thiha (Male)",
    agentTtsVoiceFemale: "Nilar (Female)",
    agentTtsExamplesHeader: "Text Examples",
    agentTtsGenerateButton: "Generate Audio",
    agentTtsLoading: "Generating audio...",
    agentTtsError: "Error: Please enter some text.",
    agentTtsResultHeader: "Result",
    // Agent Naming
    agentNameTitle: "Myanmar Name Generation",
    agentNameSubtitle: "Generate beautiful Myanmar names based on your date of birth, gender, and desired syllable count.",
    agentNameDobLabel: "Date of Birth",
    agentNameGenderLabel: "Gender",
    agentNameGenderSelect: "Select Gender",
    agentNameGenderMale: "Male",
    agentNameGenderFemale: "Female",
    agentNameSyllableLabel: "Syllable Count",
    agentNameSyllablePlaceholder: "Syllable count (e.g., 2, 3)",
    agentNameGenerateButton: "Generate Names",
    agentNameClearButton: "Clear",
    agentNameResultHeader: "Generated Names (10)",
    agentNameDayLabel: "Myanmar Birth Day",
    agentNameResultPlaceholder: "Myanmar names will be shown here.",
    agentNameDayPlaceholder: "Your birth day will be shown here.",
    agentNameLoading: "Generating...",
    agentNameWaiting: "Please wait...",
    agentNameSuccess: "Name generation successful.",
    agentNameErrorPrompt: "Date of Birth, Gender, and Syllable Count (at least 1) are required.",
    agentNameErrorApi: "Name generation error:",
    // Agent PDF Extractor
    agentPdfPageTitle: "AI PDF Extractor (Burmese)",
    agentPdfSubtitle: "*** Please use a VPN before proceeding ***",
    agentPdfUploadLabel: "Upload PDF (Max ~10MB)",
    agentPdfDropzone: "Drag & Drop PDF or click to select",
    agentPdfSelectedFile: "Selected File:",
    agentPdfErrorSize: "File size exceeds 10MB limit. Please select a smaller file.",
    agentPdfErrorType: "Please select a valid PDF file (.pdf).",
    agentPdfErrorSelect: "Please select a PDF file first.",
    agentPdfStatusComplete: "Extraction complete.",
    agentPdfStatusFailed: "Extraction failed. See details above.",
    agentPdfStatusNoDownload: "No content to download.",
    agentPdfStatusDownloaded: "File downloaded successfully as .doc!",
    agentPdfModeLabel: "Processing Mode",
    agentPdfModeFull: "Full Content",
    agentPdfModeSummarize: "Summarize",
    agentPdfModeKeypoints: "Keypoints",
    agentPdfProcessing: "Processing...",
    agentPdfExtractButton: "Extract Content",
    agentPdfDownloadButton: "Download Word File (.doc)",
    agentPdfResultPlaceholder: "The extracted content will appear here...",
    // Law AI Chatbot
    agentLawAIPageTitle: "Myanmar Law AI Chatbot",
    agentLawAIWelcome: "Hello! I am the Myanmar Law AI Chatbot. You can ask me about the laws of Myanmar.",
    agentLawAIPlaceholder: "Ask legal questions...",
    agentLawAIError: "Sorry, an error occurred. Please try again in a moment.",
    // Agent Speech to Speech
    agentS2sPageTitle: "Speech to Speech Translation",
    agentS2sPageSubtitle: "Translate your voice from one language to another using Gemini.",
    agentS2sProcessButton: "Translate Speech",
    agentS2sProcessingButton: "Translating...",
    agentS2sTranscription: "Transcription",
    agentS2sTranslation: "Translation Text",
    agentS2sResultHeader: "Translated Audio",
  },
  my: {
    headerTitle: "NAIIP",
    settingsAriaLabel: "ချိန်ညှိချက်များ",
    languageAriaLabel: "ဘာသာစကား",
    // Dashboard
    dashboardTitle: "အမျိုးသားဉာဏ်ရည်တုနည်းပညာဖွံ့ဖြိုးတိုးတက်ရေးစီမံကိန်း",
    dashboardSubtitle: "စတင်ရန် ဝန်ဆောင်မှုတစ်ခုကို ရွေးချယ်ပါ။",
    asrTitle: "ASR စနစ်",
    asrDescription: "မြန်မာစကားပြောကို စာသားအဖြစ်သို့ ပြောင်းလဲပေးသည်။",
    translateTitle: "ဘာသာပြန်စနစ်",
    translateDescription: "မြန်မာနှင့် အင်္ဂလိပ်ကြား ဘာသာပြန်ပေးသည်။",
    ttsTitle: "စာသားမှ အသံ (TTS)",
    ttsDescription: "မြန်မာစာသားကို သဘာဝကျသော အသံအဖြစ် ပြောင်းလဲပေးသည်။",
    ocrTitle: "မြန်မာ OCR",
    ocrDescription: "ပုံများအတွင်းမှ စာသားများကို ထုတ်ယူပေးသည်။",
    spellcheckTitle: "မြန်မာသတ်ပုံစစ်ခြင်း",
    spellcheckDescription: "စာသားထဲမှ သတ်ပုံအမှားများကို ပြင်ပေးသည်။",
    agentTitle: "AI Agent Bot",
    agentDescription: "အထူးပြု AI လက်ထောက်များကို အသုံးပြုနိုင်သည်။",
    // Back Button Aria
    backToDashboard: "ပင်မစာမျက်နှာသို့ ပြန်သွားမည်",
    backToAgent: "AI Agent ပင်မစာမျက်နှာသို့ ပြန်သွားမည်",
    backToTTS: "TTS မော်ဒယ်များသို့ ပြန်သွားမည်",
    back: "နောက်သို့",
    // ASR Page
    asrPageTitle: "Myanmar ASR System",
    asrPageSubtitle: "မြန်မာစကားပြောကို စာသားအဖြစ်သို့ အလိုအလျောက်ပြောင်းလဲပေးသောစနစ်",
    asrLoading: "လုပ်ဆောင်နေသည်...",
    asrPleaseWait: "ကျေးဇူးပြု၍ ခဏစောင့်ပါ",
    asrErrorOccurred: "အမှားတစ်ခု ဖြစ်ပွားခဲ့သည်",
    asrDropzonePrompt: "ဖိုင်ကို ဒီနေရာသို့ဆွဲထည့်ပါ",
    asrOr: "သို့မဟုတ်",
    asrBrowse: "ဖိုင်ရွေးရန်",
    asrStopRecording: "အသံဖမ်းခြင်းကို ရပ်ရန်",
    asrStartRecording: "အသံဖမ်းခြင်းကို စတင်ရန်",
    asrResultHeader: "စနစ်မှ ပြန်လည်ဖြေကြားချက်",
    asrSpellCheck: "သတ်ပုံစစ်ရန်",
    asrCopyToClipboard: "ကူးယူရန်",
    asrPlaceholder: "သင်၏ စာသားများ ဤနေရာတွင် ပေါ်လာမည်...",
    asrAudioError: "သင်၏ browser သည် audio element ကို အထောက်အပံ့မပေးပါ။",
    asrFooter:  "© 2025 Created by NAIIP. All rights reserved.",
    asrMicError: "မိုက်ခရိုဖုန်း အသုံးပြုခွင့်ကို ပယ်ချခဲ့သည်။ ကျေးဇူးပြု၍ သင်၏ browser ဆက်တင်များတွင် မိုက်ခရိုဖုန်း အသုံးပြုခွင့်ကို ခွင့်ပြုပါ။",
    asrFileError: "ကျေးဇူးပြု၍ အသံဖိုင်တစ်ခု ထည့်ပါ။",
    // Machine Translate Page
    mtPageTitle: "ဘာသာပြန်စနစ်",
    mtPageSubtitle: "ဘာသာစကားတစ်ခုမှ နောက်တစ်ခုသို့ စာသားများကို ပြန်ဆိုပေးခြင်း",
    mtLangMy: "မြန်မာ",
    mtLangEn: "အင်္ဂလိပ်",
    mtPlaceholderMy: "စာသားကိုဤနေရာတွင်ရိုက်ထည့်ပါ...",
    mtPlaceholderEn: "စာသားကိုဤနေရာတွင်ရိုက်ထည့်ပါ...",
    mtResultPlaceholder: "ရလဒ် ဤနေရာတွင် ပေါ်လာမည်...",
    mtTranslateButton: "ဘာသာပြန်ရန်",
    mtSwap: "ဘာသာစကားများ လဲလှယ်ရန်",
    mtCopy: "ဘာသာပြန်စာသားကို ကူးယူရန်",
    mtCopyError: "စာသားကို ကူးယူ၍မရပါ။",
    mtFooter:  "© 2025 Created by NAIIP. All rights reserved.",
    mtExampleText: "နမူနာ စာသားများ",
    // Spellcheck Page (Gemini)
    spellcheckPageTitle: "သတ်ပုံနှင့် သဒ္ဒါစစ်ဆေးခြင်း",
    spellcheckPageSubtitle: "သတ်ပုံအမှားများကို Gemini AI ဖြင့်စစ်ဆေးပေးသည်",
    spellcheckInputLabel: "စာသားထည့်ရန်",
    spellcheckPlaceholder: "စာသားကိုဤနေရာတွင်ရိုက်ထည့်ပါ...",
    spellcheckCheckButton: "စာသားစစ်ဆေးရန်",
    spellcheckResultHeader: "ပြင်ဆင်ရန်စာသား",
    spellcheckCopy: "ပြင်ဆင်ပြီးစာသားကို ကူးယူရန်",
    spellcheckLoading: "Gemini AI ဖြင့် စစ်ဆေးနေသည်...",
    spellcheckFooter: "© 2025 Created by NAIIP. All rights reserved.",
    spellcheckExampleText: "နမူနာ စာသားများ",
    // TTS Dashboard
    ttsDashboardTitle: "စာသားမှ အသံ (TTS)",
    ttsDashboardSubtitle: "အသံထွက်ရန် အသံမော်ဒယ်တစ်ခုကို ရွေးချယ်ပါ။",
    ttsCardModel1: "မော်ဒယ် ၁ (ပါချုပ်ဆရာတော်ဘုရားကြီး)",
    ttsCardModel2: "မော်ဒယ် ၂ (သီတဂူဆရာတော်ဘုရားကြီး)",
    ttsCardModel3: "မော်ဒယ် ၃ (အထွေထွေသုံး)",
    // TTS Models (General)
    ttsModelTitlePrefix: "TTS:",
    ttsModel1Name: "မော်ဒယ် ၁ (ပါချုပ်ဆရာတော်ဘုရားကြီး)",
    ttsModel2Name: "မော်ဒယ် ၂ (သီတဂူဆရာတော်ဘုရားကြီး)",
    ttsModel3Name: "မော်ဒယ် ၃ (အထွေထွေသုံး)",
    ttsInputLabel: "စာသားထည့်ပါ",
    ttsPlaceholder: "မြန်မာစာသားကို ဤနေရာတွင် ထည့်ပါ...",
    ttsRemoveSilence: "တိတ်ဆိတ်မှုကို ဖယ်ရှားရန်",
    ttsSpeed: "အမြန်နှုန်း:",
    ttsPhraseLimit: "စကားစု ကန့်သတ်ချက်",
    ttsGenerateButton: "အသံထွက်ရန်",
    ttsResultHeader: "ထုတ်လုပ်ထားသော အသံ",
    ttsLoadingPlaceholder: "ခေတ္တစောင့်ပါ....",
    ttsExampleText: "နမူနာ စာသား",
    ttsGender: "ကျား/မ",
    ttsMale: "ကျား",
    ttsFemale: "မ",
    // OCR Page
    ocrPageTitle: "မြန်မာ OCR",
    ocrPageSubtitle: "ပုံများအတွင်းမှ မြန်မာစာသားများကို ထုတ်ယူပေးခြင်း",
    ocrDropzone: "ဓာတ်ပုံကို ရွေးချယ်ပါ (သို့မဟုတ်) ဒီနေရာသို့ ဆွဲထည့်ပါ",
    ocrOriginalHeader: "ထည့်သွင်းပုံ (Original)",
    ocrResultHeader: "ရလဒ်ပုံ",
    ocrOriginalPlaceholder: "ပုံရွေးရန် စောင့်ဆိုင်းနေသည်",
    ocrResultPlaceholder: "OCR ရလဒ် ဤနေရာတွင် ပေါ်လာမည်",
    ocrExtractButton: "စာသားထုတ်ယူပါ",
    ocrProcessingButton: "လုပ်ဆောင်နေပါသည်...",
    ocrClearButton: "ရှင်းလင်းပါ",
    ocrSuccessMessage: "ပုံမှ စာသားကို အောင်မြင်စွာ ထုတ်ယူပြီးပါပြီ။",
    ocrClearedMessage: "အားလုံးကို ရှင်းလင်းပြီးပါပြီ။",
    ocrFileError: "ကျေးဇူးပြု၍ ပုံဖိုင်တစ်ခု ရွေးချယ်ပါ။",
    ocrFooter: "© 2025 Created by NAIIP. All rights reserved.",
    // AI Agent Dashboard
    agentPageTitle: "AI Agent Bot",
    agentPageSubtitle: "သင်၏ အထူးပြု AI လက်ထောက်များ။",
    agentSummarizeTitle: "မြန်မာစာ အကျဉ်းချုပ်",
    agentSummarizeDesc: "မြန်မာစာသားရှည်များကို အတိုချုံ့ပေးသည်။",
    agentOcrTitle: "မြန်မာ OCR (Gemini)",
    agentOcrDesc: "ပုံများမှ မြန်မာစာသားများကို AI ဖြင့် ထုတ်ယူပေးသည်။",
    agentTranslateTitle: "ဘာသာပြန်စနစ်",
    agentTranslateDesc: "Gemini ဖြင့် ဘာသာစကားများအကြား ပြန်ဆိုပေးသည်။",
    agentSpeechTranslateTitle: "စကားပြောမှ ဘာသာပြန်",
    agentSpeechTranslateDesc: "တစ်ဆင့်တည်းဖြင့် စကားပြောကို စာသားပြောင်းပြီး ဘာသာပြန်ပေးသည်။",
    agentSpellcheckTitle: "သတ်ပုံနှင့် သဒ္ဒါစစ်ဆေးခြင်း",
    agentSpellcheckDesc: "မြန်မာစာသားမှ အမှားများကို AI ဖြင့် ပြင်ပေးသည်။",
    agentSttTitle: "စကားပြောမှ စာသား",
    agentSttDesc: "Gemini ဖြင့် မြန်မာစကားပြောကို စာသားပြောင်းပေးသည်။",
    agentTtsTitle: "စာသားမှ စကားပြော",
    agentTtsDesc: "သဘာဝကျသော မြန်မာအသံကို ထုတ်ပေးသည်။",
    agentNamingTitle: "နာမည်ပေးခြင်း",
    agentNamingDesc: "ရိုးရာအစဉ်အလာအရ မြန်မာနာမည်များကို ထုတ်လုပ်ပေးသည်။",
    agentPdfTitle: "PDF မှ အချက်အလက်ထုတ်ယူခြင်း",
    agentPdfDesc: "PDF စာရွက်စာတမ်းများမှ စာသားနှင့် အချက်အလက်များကို ထုတ်ယူပေးသည်။",
    agentLawAITitle: "မြန်မာ့ဥပဒေ AI Chatbot",
    agentLawAIDesc: "မြန်မာနိုင်ငံ၏ ဥပဒေရေးရာ မေးခွန်းများ မေးမြန်းရန်။",
    agentS2sTitle: "စကားပြောမှ စကားပြော",
    agentS2sDesc: "စကားပြောဘာသာစကားတစ်ခုကို အခြားတစ်ခုသို့ ပြန်ဆိုပေးသည်။",
    // Old Spellcheck Page
    oldSpellcheckTitle: "သတ်ပုံစစ်ခြင်း",
    oldSpellcheckSubtitle: "သတ်ပုံအမှားများကို စစ်ဆေးပေးသည်",
    oldSpellcheckResultHeader: "ပြင်ဆင်ပြီးစာသား",
    oldSpellcheckLoading: "အမှားများ စစ်ဆေးနေသည်...",
    oldSpellcheckFooter:  "© 2025 Created by NAIIP. All rights reserved.",
    // Summarize Page
    summarizeTitle: "မြန်မာစာ အကျဉ်းချုပ်",
    summarizeSubtitle: "စာသားရှည်များကို Gemini AI ဖြင့် အတိုချုံ့ပေးသည်",
    summarizeInputLabel: "စာသားအရှည်ထည့်ရန်",
    summarizePlaceholder: "စာသားရှည်ကို ဤနေရာတွင် ကူးထည့်ပါ...",
    summarizeButton: "အကျဉ်းချုပ်ရန်",
    summarizeResultHeader: "အကျဉ်းချုပ်",
    summarizeLoading: "Gemini AI ဖြင့် အကျဉ်းချုပ်နေသည်...",
    summarizeFooter: "© 2025 Created by NAIIP. All rights reserved.",
    // Agent OCR
    agentOcrPageTitle: "မြန်မာ OCR (Gemini)",
    agentOcrSubtitle: "ပုံများမှ မြန်မာစာသားများကို AI ဖြင့် ထုတ်ယူပါ",
    agentOcrUploadImageLabel: "၁. ဓာတ်ပုံထည့်သွင်းပါ",
    agentOcrDropzonePrompt: "ပုံကိုဤနေရာသို့ဆွဲထည့်ပါ သို့မဟုတ် ရွေးချယ်ရန်နှိပ်ပါ",
    agentOcrSelectedFile: "ရွေးချယ်ထားသောဖိုင်:",
    agentOcrOriginalImageLabel: "မူရင်းပုံ",
    agentOcrExtractedTextLabel: "ထုတ်ယူထားသောစာသား",
    agentOcrPlaceholder: "စာသားထုတ်ယူပြီးနောက် ဤနေရာတွင်ပေါ်လာပါမည်...",
    agentOcrExtractButton: "စာသားထုတ်ယူပါ",
    agentOcrExtractingButton: "လုပ်ဆောင်နေသည်...",
    agentOcrCopyButtonTitle: "စာသားကူးယူပါ",
    agentOcrErrorNotImage: "ကျေးဇူးပြု၍ ပုံဖိုင်အမှန်ကို ရွေးချယ်ပါ။",
    agentOcrErrorNoFile: "စာသားမထုတ်မီ ပုံဖိုင်ကို ဦးစွာရွေးချယ်ပါ။",
    agentOcrErrorUnknown: "ထုတ်ယူနေစဉ် အမည်မသိအမှားတစ်ခု ဖြစ်ပွားခဲ့သည်။",
    // Agent Machine Translation
    agentMtTitle: "ဘာသာပြန်စနစ် (Gemini)",
    agentMtSubtitle: "Gemini AI ဖြင့် ဘာသာစကားများအကြား ပြန်ဆိုပါ",
    agentMtLangBurmese: "မြန်မာ",
    agentMtLangEnglish: "အင်္ဂလိပ်",
    agentMtPlaceholderBurmese: "စာသားကိုဤနေရာတွင်ရိုက်ထည့်ပါ...",
    agentMtPlaceholderEnglish: "စာသားကိုဤနေရာတွင်ရိုက်ထည့်ပါ...",
    agentMtResultPlaceholder: "ဘာသာပြန်စာသား ဤနေရာတွင် ပေါ်လာမည်...",
    // Speech to Translate Page
    sttPageTitle: "စကားပြောမှ ဘာသာပြန် (Gemini)",
    sttPageSubtitle: "စကားပြောကို စာသားအဖြစ်ပြောင်းပြီး ဘာသာပြန်ပါ",
    sttDropzonePrompt: "အသံဖိုင်ကို ဆွဲထည့်ပါ",
    sttUpload: "သို့မဟုတ် တင်ရန် နှိပ်ပါ",
    sttRecord: "သို့မဟုတ် အသံဖမ်းပါ",
    sttResultTranscription: "မူရင်းစာသား",
    sttResultTranslation: "ဘာသာပြန် (အင်္ဂလိပ်)",
    sttLoading: "Gemini AI ဖြင့် လုပ်ဆောင်နေသည်...",
    sttMicError: "မိုက်ခရိုဖုန်း အသုံးပြုခွင့်ကို ပယ်ချခဲ့သည်။",
    sttFileError: "ကျေးဇူးပြု၍ အသံဖိုင်တစ်ခု ထည့်ပါ။",
    // Agent Speech to Text
    agentSttPageTitle: "စကားပြောမှ စာသား (Gemini)",
    agentSttPageSubtitle: "Gemini ဖြင့် မြန်မာစကားပြောကို စာသားပြောင်းပေးသည်။",
    agentSttDropzonePrompt: "အသံဖိုင် ဆွဲထည့်ပါ",
    agentSttChooseFile: "ဖိုင်ရွေးပါ",
    agentSttResultHeader: "စာသားရလဒ်",
    agentSttPlaceholder: "သင်၏ စာသားများ ဤနေရာတွင် ပေါ်လာမည်...",
    agentSttLoading: "Gemini ဖြင့် စာသားပြောင်းနေသည်...",
    agentSttLoadingWait: "ကျေးဇူးပြု၍ ခဏစောင့်ပါ။",
    // Agent Text to Speech
    agentTtsPageTitle: "စာသားမှ စကားပြော",
    agentTtsPageSubtitle: "စာသားမှ သဘာဝကျသော အသံကို ထုတ်ပေးသည်။",
    agentTtsInputLabel: "စာသား ထည့်သွင်းရန်",
    agentTtsPlaceholder: "ဒီနေရာမှာ စာသား ရိုက်ထည့်ပါ...",
    agentTtsSettingsHeader: "ချိန်ညှိချက်များ",
    agentTtsVoiceLabel: "အသံ ရွေးချယ်ရန်",
    agentTtsVoiceMale: "သီဟ (ကျား)",
    agentTtsVoiceFemale: "နီလာ (မ)",
    agentTtsExamplesHeader: "နမူနာ စာသားများ",
    agentTtsGenerateButton: "အသံဖန်တီးပါ",
    agentTtsLoading: "အသံဖိုင် ဖန်တီးနေပါသည်...",
    agentTtsError: "❌ အမှား: ကျေးဇူးပြု၍ စာသားအချို့ ထည့်ပါ။",
    agentTtsResultHeader: "ရလဒ်",
    // Agent Naming
    agentNameTitle: "မြန်မာ နာမည်ထုတ်လုပ်ရေး",
    agentNameSubtitle: "သင်၏မွေးသက္ကရာဇ်၊ ကျား/မ နှင့် စာလုံးအရေအတွက်ကို ရွေးချယ်ပြီး လှပသော မြန်မာနာမည်များကို ထုတ်လုပ်ပါ။",
    agentNameDobLabel: "မွေးသက္ကရာဇ်",
    agentNameGenderLabel: "ကျား/မ",
    agentNameGenderSelect: "ကျား/မ ရွေးချယ်ပါ",
    agentNameGenderMale: "ကျား",
    agentNameGenderFemale: "မ",
    agentNameSyllableLabel: "စာလုံးအရေအတွက်",
    agentNameSyllablePlaceholder: "စာလုံးအရေအတွက် (ဥပမာ: ၂, ၃)",
    agentNameGenerateButton: "နာမည်ထုတ်လုပ်ပါ",
    agentNameClearButton: "ရှင်းလင်းပါ",
    agentNameResultHeader: "ထုတ်လုပ်ထားသော နာမည် (၁၀ ခု)",
    agentNameDayLabel: "မြန်မာ မွေးနေ့",
    agentNameResultPlaceholder: "မြန်မာနာမည်များကို ဤနေရာတွင် ဖော်ပြပါမည်။",
    agentNameDayPlaceholder: "မွေးနေ့ကို ဤနေရာတွင် ဖော်ပြပါမည်။",
    agentNameLoading: "ထုတ်လုပ်နေသည်...",
    agentNameWaiting: "ခေတ္တစောင့်ပါ....",
    agentNameSuccess: "နာမည်ထုတ်လုပ်မှု အောင်မြင်ပါပြီ။",
    agentNameErrorPrompt: "မွေးသက္ကရာဇ်၊ ကျား/မ နှင့် စာလုံးအရေအတွက် (အနည်းဆုံး ၁) ကို ရွေးချယ်ရန် လိုအပ်ပါသည်။",
    agentNameErrorApi: "နာမည်ထုတ်လုပ်မှု အမှား:",
    // Agent PDF Extractor
    agentPdfPageTitle: "AI PDF မှ အချက်အလက်ထုတ်ယူခြင်း (မြန်မာ)",
    agentPdfSubtitle: "*** VPN ခံပြီးမှသာ အသုံးပြုပေးပါရန် ***",
    agentPdfUploadLabel: "PDF တင်ရန် (အများဆုံး ~10MB)",
    agentPdfDropzone: "PDF ကိုဆွဲထည့်ပါ သို့မဟုတ် ရွေးချယ်ရန်နှိပ်ပါ",
    agentPdfSelectedFile: "ရွေးချယ်ထားသောဖိုင်:",
    agentPdfErrorSize: "ဖိုင်အရွယ်အစား 10MB ထက်ကျော်လွန်နေသည်။ ကျေးဇူးပြု၍ ဖိုင်ငယ်တစ်ခုကို ရွေးချယ်ပါ။",
    agentPdfErrorType: "ကျေးဇူးပြု၍ PDF ဖိုင် (.pdf) အမှန်ကို ရွေးချယ်ပါ။",
    agentPdfErrorSelect: "ကျေးဇူးပြု၍ PDF ဖိုင်ကို ဦးစွာရွေးချယ်ပါ။",
    agentPdfStatusComplete: "ထုတ်ယူခြင်း ပြီးสมบูรณ์แล้ว",
    agentPdfStatusFailed: "ထုတ်ယူခြင်း မအောင်မြင်ပါ။ အသေးစိတ်ကို အထက်တွင် ကြည့်ပါ။",
    agentPdfStatusNoDownload: "ဒေါင်းလုဒ်လုပ်ရန် အကြောင်းအရာမရှိပါ။",
    agentPdfStatusDownloaded: ".doc ဖိုင်အဖြစ် အောင်မြင်စွာ ဒေါင်းလုဒ်လုပ်ပြီးပါပြီ။",
    agentPdfModeLabel: "လုပ်ဆောင်မှုမုဒ်",
    agentPdfModeFull: "အကြောင်းအရာ အပြည့်အစုံ",
    agentPdfModeSummarize: "အကျဉ်းချုပ်",
    agentPdfModeKeypoints: "အဓိကအချက်များ",
    agentPdfProcessing: "လုပ်ဆောင်နေသည်...",
    agentPdfExtractButton: "အကြောင်းအရာ ထုတ်ယူပါ",
    agentPdfDownloadButton: "Word ဖိုင် (.doc) ဒေါင်းလုဒ်လုပ်ပါ",
    agentPdfResultPlaceholder: "ထုတ်ယူထားသော အကြောင်းအရာ ဤနေရာတွင် ပေါ်လာမည်...",
    // Law AI Chatbot
    agentLawAIPageTitle: "မြန်မာ့ဥပဒေ AI Chat Bot",
    agentLawAIWelcome: "မင်္ဂလာပါ! ကျွန်တော်က မြန်မာ့ဥပဒေရေးရာ AI Chat Bot ပါ။ မြန်မာနိုင်ငံ၏ ဥပဒေများနှင့် ပတ်သက်၍ မေးမြန်းနိုင်ပါတယ်ခင်ဗျာ။",
    agentLawAIPlaceholder: "ဥပဒေရေးရာ မေးခွန်းများ မေးမြန်းပါ...",
    agentLawAIError: "တောင်းပန်ပါတယ်၊ အမှားတစ်ခုဖြစ်သွားလို့ပါ။ ခဏနေ ပြန်ကြိုးစားပေးပါ။",
    // Agent Speech to Speech
    agentS2sPageTitle: "စကားပြောမှ စကားပြော ဘာသာပြန်ခြင်း",
    agentS2sPageSubtitle: "သင်၏အသံကို Gemini သုံး၍ ဘာသာစကားတစ်ခုမှ အခြားတစ်ခုသို့ ပြန်ဆိုပါ။",
    agentS2sProcessButton: "စကားပြော ဘာသာပြန်ရန်",
    agentS2sProcessingButton: "ဘာသာပြန်နေသည်...",
    agentS2sTranscription: "စာသားမှတ်တမ်း",
    agentS2sTranslation: "ဘာသာပြန်စာသား",
    agentS2sResultHeader: "ဘာသာပြန်ပြီး အသံ",
  }
};

type Language = 'en' | 'my';
type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('my');

  const t = (key: TranslationKey): string => {
    return translations[language][key] || translations['en'][key];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
